version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: "http://server:9090"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5433/shareit"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "12345"
    extra_hosts:
      - "host.docker.internal:host-gateway"